export const en = {
  moduleName: "Cervical Cancer Screening (VIA)",
  patientContext: "Patient Context",
  ageBandLabel: "Patient Age Range",
  ageBand2529: "25–29 years",
  ageBand3034: "30–34 years",
  ageBand3539: "35–39 years",
  ageBand4044: "40–44 years",
  ageBand4549: "45–49 years",
  ageBand50plus: "50+ years",
  screeningContextLabel: "Screening Reason",
  screeningRoutine: "Routine screening",
  screeningReferral: "Referral",
  screeningHpv: "HPV-positive triage",
  notesLabel: "Notes (optional)",
  notesDisclaimer: "Notes are stored on this device only and never uploaded.",
  captureGuideTitle: "Image Capture Guide",
  captureGuideDesc: "Position the device 15–20 cm from the cervix. Ensure the area is well lit. Hold steady.",
  skipCertified: "Skip — I'm certified",
  captureBtn: "Capture Image",
  uploadBtn: "Upload from Gallery",
  qualityChecking: "Checking image quality…",
  qualityBlurFail: "Image blurry — hold the device steady",
  qualityExposureFail: "Image too dark or too bright — adjust lighting",
  qualityFramingFail: "Cervix not detected — reposition the device",
  qualityOverrideBtn: "Continue anyway — result confidence may be lower",
  qualityAttemptsRemaining: "Attempts remaining: ",
  analysing: "Analysing image…",
  resultPositive: "POSITIVE",
  resultNegative: "NEGATIVE",
  resultRefer: "REFER",
  confidenceHigh: "HIGH CONFIDENCE",
  confidenceModerate: "MODERATE CONFIDENCE",
  confidenceLow: "LOW CONFIDENCE",
  confidenceReference: "REFERENCE ONLY",
  confidenceHighDesc: "Result from validated on-device or online AI model.",
  confidenceModerateDesc: "Result based on visual observations. Verify with supervisor if unsure.",
  confidenceLowDesc: "Low confidence — result overridden to REFER for clinical safety.",
  confidenceReferenceDesc: "Reference material only. No analysis performed. Escalate to supervisor.",
  actionLabel: "Action Taken",
  actionTreated: "Treated",
  actionReferred: "Referred",
  actionMonitored: "Monitored",
  actionDeclined: "Declined",
  saveEncounter: "Save Encounter",
  encounterSaved: "Encounter saved.",
  newScreening: "New Screening",
  fallbackQ1: "Is there a white patch on the cervix after applying the acid?",
  fallbackQ2: "Does the white patch touch the central opening (os)?",
  fallbackQ3: "Is the white patch raised or has an irregular border?",
  fallbackActionPositive: "Acetowhite lesion detected. Refer for colposcopy or consider same-visit cryotherapy if eligible.",
  fallbackActionNegative: "No acetowhite lesion detected. Routine rescreening in 3 years.",
  fallbackActionRefer: "Indeterminate findings. Escalate to supervising clinician.",
  ruleBasedLabel: "RULE-BASED RESULT — No image analysis performed",
  onlineAiLabel: "Online AI used",
  onlineAiCost: "estimated cost",
  inferenceOnDevice: "On-device AI",
  inferenceGemini: "Online AI: Gemini",
  inferenceGpt4o: "Online AI: GPT-4o",
  inferenceRuleBased: "Offline guidance",
  inferenceReference: "Reference only",
  recommendedActionPositive: "Refer for colposcopy or same-visit cryotherapy if eligible.",
  recommendedActionNegative: "Routine rescreening in 3 years.",
  recommendedActionRefer: "Escalate to supervising clinician.",
};
