export const fr = {
  moduleName: "Dépistage du Cancer du Col (VIA)",
  patientContext: "Contexte Patient",
  ageBandLabel: "Tranche d'Âge du Patient",
  ageBand2529: "25–29 ans",
  ageBand3034: "30–34 ans",
  ageBand3539: "35–39 ans",
  ageBand4044: "40–44 ans",
  ageBand4549: "45–49 ans",
  ageBand50plus: "50 ans et plus",
  screeningContextLabel: "Raison du Dépistage",
  screeningRoutine: "Dépistage de routine",
  screeningReferral: "Référence",
  screeningHpv: "Triage HPV positif",
  notesLabel: "Notes (optionnel)",
  notesDisclaimer: "Les notes sont stockées sur cet appareil uniquement et ne sont jamais transmises.",
  captureGuideTitle: "Guide de Capture d'Image",
  captureGuideDesc: "Positionnez l'appareil à 15–20 cm du col. Assurez un bon éclairage. Restez stable.",
  skipCertified: "Passer — Je suis certifié(e)",
  captureBtn: "Capturer l'Image",
  uploadBtn: "Charger depuis la Galerie",
  qualityChecking: "Vérification de la qualité…",
  qualityBlurFail: "Image floue — maintenez l'appareil stable",
  qualityExposureFail: "Image trop sombre ou trop claire — ajustez l'éclairage",
  qualityFramingFail: "Col non détecté — repositionnez l'appareil",
  qualityOverrideBtn: "Continuer quand même — la confiance peut être réduite",
  qualityAttemptsRemaining: "Tentatives restantes : ",
  analysing: "Analyse en cours…",
  resultPositive: "POSITIF",
  resultNegative: "NÉGATIF",
  resultRefer: "RÉFÉRER",
  confidenceHigh: "CONFIANCE ÉLEVÉE",
  confidenceModerate: "CONFIANCE MODÉRÉE",
  confidenceLow: "CONFIANCE FAIBLE",
  confidenceReference: "RÉFÉRENCE SEULEMENT",
  confidenceHighDesc: "Résultat d'un modèle AI validé.",
  confidenceModerateDesc: "Résultat basé sur des observations visuelles. Vérifiez avec un superviseur en cas de doute.",
  confidenceLowDesc: "Faible confiance — résultat remplacé par RÉFÉRER pour la sécurité clinique.",
  confidenceReferenceDesc: "Matériel de référence seulement. Aucune analyse. Escaladez au superviseur.",
  actionLabel: "Action Prise",
  actionTreated: "Traité",
  actionReferred: "Référé",
  actionMonitored: "Surveillé",
  actionDeclined: "Refusé",
  saveEncounter: "Enregistrer la Consultation",
  encounterSaved: "Consultation enregistrée.",
  newScreening: "Nouveau Dépistage",
  fallbackQ1: "Y a-t-il une tache blanche sur le col après l'application de l'acide ?",
  fallbackQ2: "La tache blanche touche-t-elle l'orifice central (os) ?",
  fallbackQ3: "La tache blanche est-elle surélevée ou a-t-elle un bord irrégulier ?",
  fallbackActionPositive: "Lésion acéto-blanche détectée. Référer pour colposcopie ou envisager la cryothérapie si éligible.",
  fallbackActionNegative: "Aucune lésion acéto-blanche. Redépistage de routine dans 3 ans.",
  fallbackActionRefer: "Résultats indéterminés. Escaladez au clinicien superviseur.",
  ruleBasedLabel: "RÉSULTAT BASÉ SUR DES RÈGLES — Aucune analyse d'image",
  onlineAiLabel: "AI en ligne utilisée",
  onlineAiCost: "coût estimé",
  inferenceOnDevice: "AI sur appareil",
  inferenceGemini: "AI en ligne : Gemini",
  inferenceGpt4o: "AI en ligne : GPT-4o",
  inferenceRuleBased: "Guidance hors ligne",
  inferenceReference: "Référence seulement",
  recommendedActionPositive: "Référer pour colposcopie ou cryothérapie si éligible.",
  recommendedActionNegative: "Redépistage de routine dans 3 ans.",
  recommendedActionRefer: "Escaladez au clinicien superviseur.",
};
