export const ha = {
  moduleName: "Gwajin Cutar Mahaifa (VIA)",
  patientContext: "Bayanin Majinyaci",
  ageBandLabel: "Shekarun Majinyaci",
  ageBand2529: "Shekara 25–29",
  ageBand3034: "Shekara 30–34",
  ageBand3539: "Shekara 35–39",
  ageBand4044: "Shekara 40–44",
  ageBand4549: "Shekara 45–49",
  ageBand50plus: "Shekara 50+",
  screeningContextLabel: "Dalilin Gwajin",
  screeningRoutine: "Gwajin yau da kullum",
  screeningReferral: "An aika",
  screeningHpv: "Gwajin HPV-positive",
  notesLabel: "Bayanan ƙarin (zaɓi)",
  notesDisclaimer: "Bayanai ana adana su a wannan na'ura kawai kuma ba a sakawa sama ba.",
  captureGuideTitle: "Jagoran Ɗaukar Hoto",
  captureGuideDesc: "Sanya na'ura cm 15–20 daga mahaifa. Tabbatar wurin yana da haske. Riƙe a tsaye.",
  skipCertified: "Tsallake — Na samu takardar shedar",
  captureBtn: "Ɗauki Hoto",
  uploadBtn: "Loda daga Galari",
  qualityChecking: "Ana duba ingancin hoto…",
  qualityBlurFail: "Hoto ba a fili ba — riƙe na'ura a tsaye",
  qualityExposureFail: "Hoto mai duhu ko haske — daidaita hasken",
  qualityFramingFail: "Ba a gano mahaifa — sake sanya na'ura",
  qualityOverrideBtn: "Ci gaba ta kowace hanya — ingancin sakamakon zai ragu",
  qualityAttemptsRemaining: "Sauran damar gwaji: ",
  analysing: "Ana nazarin hoto…",
  resultPositive: "TABBATACCE",
  resultNegative: "MARA CUTAR",
  resultRefer: "AIKA",
  confidenceHigh: "DOGON AMINTACCEN",
  confidenceModerate: "MATSAKAICIN AMINTACCEN",
  confidenceLow: "ƘARANCIN AMINTACCEN",
  confidenceReference: "KAWAI BAYANI",
  confidenceHighDesc: "Sakamakon daga ingantaccen na'ura ta AI.",
  confidenceModerateDesc: "Sakamakon daga lura kai tsaye. Yi shawarari da mai sa ido idan ba ka tabbata ba.",
  confidenceLowDesc: "Ƙarancin amintattu — an canza sakamakon zuwa AIKA don amincin lafiya.",
  confidenceReferenceDesc: "Kawai bayani ne. Ba a yi nazari ba. Kai shi ga mai sa ido.",
  actionLabel: "Mataki da aka ɗauka",
  actionTreated: "An yi maganin",
  actionReferred: "An aika",
  actionMonitored: "An sa ido",
  actionDeclined: "Ya ƙi",
  saveEncounter: "Ajiye Gwajin",
  encounterSaved: "Gwajin an ajiye.",
  newScreening: "Sabon Gwajin",
  fallbackQ1: "Shin akwai farin tabo a mahaifa bayan shafa acid?",
  fallbackQ2: "Shin farin tabo ya taɓa tsakiyar budewa (os)?",
  fallbackQ3: "Shin farin tabo ya tashi ko yana da iyakoki mara daidaituwa?",
  fallbackActionPositive: "An gano tabo fari. Aika zuwa colposcopy ko la'akari da cryotherapy a wannan lokaci idan ta cancanta.",
  fallbackActionNegative: "Ba a gano tabo fari ba. Sake gwajin bayan shekara 3.",
  fallbackActionRefer: "Sakamakon ba a tabbata ba. Kai ga mai sa ido.",
  ruleBasedLabel: "SAKAMAKON DOKOKI — Ba a yi nazarin hoto ba",
  onlineAiLabel: "An yi amfani da AI ta yanar gizo",
  onlineAiCost: "ƙididdigar kuɗi",
  inferenceOnDevice: "AI ta na'ura",
  inferenceGemini: "AI ta yanar gizo: Gemini",
  inferenceGpt4o: "AI ta yanar gizo: GPT-4o",
  inferenceRuleBased: "Jagora ta marar intanet",
  inferenceReference: "Kawai bayani",
  recommendedActionPositive: "Aika zuwa colposcopy ko cryotherapy a wannan lokaci idan ta cancanta.",
  recommendedActionNegative: "Sake gwajin yau da kullum bayan shekara 3.",
  recommendedActionRefer: "Kai ga mai sa ido.",
};
