export const ig = {
  moduleName: "Nyocha Ọrịa Ahịhịa Nwanyị (VIA)",
  patientContext: "Ozi Onye Ọrịa",
  ageBandLabel: "Ọchịchọ Afọ Onye Ọrịa",
  ageBand2529: "Afọ 25–29",
  ageBand3034: "Afọ 30–34",
  ageBand3539: "Afọ 35–39",
  ageBand4044: "Afọ 40–44",
  ageBand4549: "Afọ 45–49",
  ageBand50plus: "Afọ 50+",
  screeningContextLabel: "Ihe Kpatara Nyocha",
  screeningRoutine: "Nyocha nke oge niile",
  screeningReferral: "Ezitere",
  screeningHpv: "Nyocha HPV dị mma",
  notesLabel: "Ndetu (nhọrọ)",
  notesDisclaimer: "A na-echekwa ndetu na ngwaọrụ a naanị, anaghị eziga ya.",
  captureGuideTitle: "Nduzi Ịse Foto",
  captureGuideDesc: "Tinye ngwaọrụ cm 15–20 site n'ahịhịa. Jide n'aka na ọ na-egbuke. Nọrọ n'otu ebe.",
  skipCertified: "Gafee — Enwere m asambodo",
  captureBtn: "Ise Foto",
  uploadBtn: "Bulite site n'Ụlọ Foto",
  qualityChecking: "Na-enyocha ogo foto…",
  qualityBlurFail: "Foto adịghị ìhè — nọrọ ngwaọrụ ike",
  qualityExposureFail: "Foto ọchịchọ ọchịm ma ọ bụ ọkụ ukwuu — dozie ìhè",
  qualityFramingFail: "Ahịhịa achọtaghị — tọgharịa ngwaọrụ",
  qualityOverrideBtn: "Gaa n'ihu — ọkọlọtọ nsonaazụ nwere ike idi nta",
  qualityAttemptsRemaining: "Ọnụọgụgụ ọgwụgwụ fọdụrụ: ",
  analysing: "Na-atụle foto…",
  resultPositive: "DỊMMA",
  resultNegative: "EZIGHI",
  resultRefer: "ZIPU",
  confidenceHigh: "NKWENYE DỊ ELU",
  confidenceModerate: "NKWENYE NKEZI",
  confidenceLow: "NKWENYE DỊWARA OBERE",
  confidenceReference: "NTỤAKA NAANỊ",
  confidenceHighDesc: "Nsonaazụ si na ngwa AI akọwapụtara.",
  confidenceModerateDesc: "Nsonaazụ dabere na nlele anya. Kpọtụrụ onye ọ bụla nlele ma ọ bụrụ na i na-adịghị mma.",
  confidenceLowDesc: "Nkwenye dị nta — nsonaazụ gbanwere na ZIPU maka nchekwa ahụike.",
  confidenceReferenceDesc: "Ntụaka naanị. Enweghị nyocha. Ziga onye nlele.",
  actionLabel: "Ihe e Mere",
  actionTreated: "Agwọọ",
  actionReferred: "Ezitere",
  actionMonitored: "Elele",
  actionDeclined: "Ajụrụ",
  saveEncounter: "Chekwaa Ọgbako",
  encounterSaved: "Ọgbako echekwara.",
  newScreening: "Nyocha Ọhụrụ",
  fallbackQ1: "Ọ dị obere ọcha ọcha na ahịhịa mgbe e tinye acid?",
  fallbackQ2: "Obere ọcha ọcha ahụ na-emetụ oghere etiti (os)?",
  fallbackQ3: "Obere ọcha ọcha ahụ pụtara elu ma ọ bụ nwere oke adịghị mma?",
  fallbackActionPositive: "Achọtara obere ọcha ọcha. Ziga maka colposcopy ma ọ bụ tụlee cryotherapy n'oge ahụ ma ọ kwalite.",
  fallbackActionNegative: "Achọtaghị obere ọcha ọcha. Nyocha oge niile na afọ 3.",
  fallbackActionRefer: "Nsonaazụ adịghị ìhè. Ziga onye nlele.",
  ruleBasedLabel: "NSONAAZỤ IWU — Enweghị nyocha foto",
  onlineAiLabel: "E jiri AI ịntaneti",
  onlineAiCost: "ọnụahịa a tụrụ anya",
  inferenceOnDevice: "AI ngwaọrụ",
  inferenceGemini: "AI ịntaneti: Gemini",
  inferenceGpt4o: "AI ịntaneti: GPT-4o",
  inferenceRuleBased: "Nduzi n'enweghị ịntaneti",
  inferenceReference: "Ntụaka naanị",
  recommendedActionPositive: "Ziga maka colposcopy ma ọ bụ cryotherapy n'oge ahụ ma ọ kwalite.",
  recommendedActionNegative: "Nyocha oge niile na afọ 3.",
  recommendedActionRefer: "Ziga onye nlele.",
};
