export const yo = {
  moduleName: "Ibojì Àrùn Ọgàn Obìnrin (VIA)",
  patientContext: "Ìsọ̀rí Aláìsàn",
  ageBandLabel: "Ọjọ Orí Aláìsàn",
  ageBand2529: "Ọdún 25–29",
  ageBand3034: "Ọdún 30–34",
  ageBand3539: "Ọdún 35–39",
  ageBand4044: "Ọdún 40–44",
  ageBand4549: "Ọdún 45–49",
  ageBand50plus: "Ọdún 50+",
  screeningContextLabel: "Ìdí Ibojì",
  screeningRoutine: "Ibojì àṣà",
  screeningReferral: "Tọka sí",
  screeningHpv: "Ibojì HPV-rere",
  notesLabel: "Àkọsílẹ̀ (àṣayan)",
  notesDisclaimer: "Àkọsílẹ̀ wà lórí ẹ̀rọ yìí nìkan kí wọn kò sì ràn sókè.",
  captureGuideTitle: "Ìtọ́nà Gbigba Àwòrán",
  captureGuideDesc: "Fi ẹ̀rọ ṣe cm 15–20 sí ọgàn. Rii dájú àgbègbè náà jẹ́ ìmọ́. Mú ìdúró.",
  skipCertified: "Fo — Mo ní ìwé-ẹ̀rí",
  captureBtn: "Gba Àwòrán",
  uploadBtn: "Gbékalẹ̀ láti Galari",
  qualityChecking: "Ń ṣàyẹ̀wò didara àwòrán…",
  qualityBlurFail: "Àwòrán kò yàwọ — jẹ́ kí ẹ̀rọ náà dúró",
  qualityExposureFail: "Àwòrán ṣokùnkùn tabi fọ́ jù — ṣe àtúnṣe ìmọ́",
  qualityFramingFail: "Ọgàn kò rí — tún gbé ẹ̀rọ",
  qualityOverrideBtn: "Bá a lọ — ìgbàgbọ́ àbájáde lè dín kù",
  qualityAttemptsRemaining: "Ìgbìyànjú tó kù: ",
  analysing: "Ń ṣe ìtúpalẹ̀ àwòrán…",
  resultPositive: "RERE",
  resultNegative: "ÒDÒDÓ",
  resultRefer: "TỌKA",
  confidenceHigh: "ÌGBÀGBỌ́ GÍGA",
  confidenceModerate: "ÌGBÀGBỌ́ ÀÁRÍN",
  confidenceLow: "ÌGBÀGBỌ́ KÉKERÉ",
  confidenceReference: "ÌTỌ́KA NÌKAN",
  confidenceHighDesc: "Àbájáde láti ọ̀dọ̀ ẹ̀rọ AI tó fọwọ́sí.",
  confidenceModerateDesc: "Àbájáde dá lórí àkíyèsí ojú aya. Bá alábójútó sọ̀rọ̀ tí o bá ṣiyèméjì.",
  confidenceLowDesc: "Ìgbàgbọ́ kékeré — àbájáde yípadà sí TỌKA fún àbò ìlera.",
  confidenceReferenceDesc: "Ìtọ́kasi nìkan. Kò sí ìtúpalẹ̀. Gbé sí alábójútó.",
  actionLabel: "Ìgbésẹ̀ tí a Ṣe",
  actionTreated: "Tọ́jú",
  actionReferred: "Tọka",
  actionMonitored: "Ṣọ́",
  actionDeclined: "Kọ̀",
  saveEncounter: "Fi Ìpadàbọ̀ Pamọ́",
  encounterSaved: "Ìpadàbọ̀ ti fipamọ́.",
  newScreening: "Ibojì Tuntun",
  fallbackQ1: "Ṣe àpẹ̀tẹ́ funfun wà lórí ọgàn lẹ́hìn títẹ́ acid?",
  fallbackQ2: "Ṣe àpẹ̀tẹ́ funfun náà fi ara mọ́ ihò àárín (os)?",
  fallbackQ3: "Ṣe àpẹ̀tẹ́ funfun náà gbéjáde tàbí ní ìlà aibáamu?",
  fallbackActionPositive: "A rí àpẹ̀tẹ́ funfun. Tọka fún colposcopy tàbí ṣe ìtóka cryotherapy tí ó bá ṣeéṣe.",
  fallbackActionNegative: "Kò sí àpẹ̀tẹ́ funfun. Ibojì àṣà lẹ́hìn ọdún 3.",
  fallbackActionRefer: "Àbájáde kò ṣe kedere. Gbé sí alábójútó.",
  ruleBasedLabel: "ÀBÁJÁDE ÌLÀNÀ — Kò sí ìtúpalẹ̀ àwòrán",
  onlineAiLabel: "AI ìntánẹ̀ẹ̀tì ti lò",
  onlineAiCost: "ìdiyèlé àṣàyàn",
  inferenceOnDevice: "AI ẹ̀rọ",
  inferenceGemini: "AI ìntánẹ̀ẹ̀tì: Gemini",
  inferenceGpt4o: "AI ìntánẹ̀ẹ̀tì: GPT-4o",
  inferenceRuleBased: "Ìtọ́nà aláìlẹ̀gbẹ̀ ìntánẹ̀ẹ̀tì",
  inferenceReference: "Ìtọ́kasi nìkan",
  recommendedActionPositive: "Tọka fún colposcopy tàbí cryotherapy ní àkókò kọ̀ọ̀kan tí ó bá ṣeéṣe.",
  recommendedActionNegative: "Ibojì àṣà lẹ́hìn ọdún 3.",
  recommendedActionRefer: "Gbé sí alábójútó.",
};
